config: !!python/object:__main__.PCRPipelineConfig
  backbone: resnet34
  batch_size: 4
  early_stopping_patience: 15
  freeze_stages: 2
  heavy_augmentation: true
  input_channels: 3
  learning_rate: 0.0001
  max_epochs: 100
  pcr_labels_csv: !!python/object/apply:pathlib.WindowsPath
  - C:\
  - Users
  - usuario
  - Documents
  - Mama_Mia
  - ganadores_pcr
  - pcr_labels.csv
  pretrained_weights: MedicalNet
  processed_data_dir: !!python/object/apply:pathlib.WindowsPath
  - D:\
  - mama_mia_fixed_0000_0001_challenge_ready
  splits_csv: !!python/object/apply:pathlib.WindowsPath
  - C:\
  - Users
  - usuario
  - Documents
  - Mama_Mia
  - datos
  - train_test_splits.csv
  target_size: !!python/tuple
  - 96
  - 96
  - 96
  unfreeze_after_epochs: 10
